FROM debian AS build
WORKDIR /pocketbase
RUN apt update &&\
    apt install -y curl unzip &&\
    curl -Lo pocketbase.zip https://github.com/pocketbase/pocketbase/releases/download/v0.11.3/pocketbase_0.11.3_linux_amd64.zip &&\
    unzip pocketbase

FROM scratch
COPY --from=build /pocketbase/pocketbase /usr/local/bin/pocketbase
EXPOSE 8090
CMD ["/usr/local/bin/pocketbase", "serve", "--http", "0.0.0.0:8090"]